schedule:
  name: Schedule an Action
  description: Schedule an action to run at a specific time or time delta
  fields:
    name:
      name: Name
      description: Name of the schedule. Shown in Logbook.
      required: false
      selector:
        text:
    id:
      name: ID
      description: ID of the schedule. Allows for future deletion, and overwrites.
      required: false
      selector:
        text:
    delay:
      name: Delay
      description: set a time delta for when the action should trigger
      required: false
      selector:
        duration:
    delay_from:
      name: Deleay From
      description: If using a Delay, optionally set when to delay from.
      required: false
      selector:
        datetime:
    trigger_time:
      name: Trigger Time
      description: set a timestamp for when the action should trigger
      required: false
      selector:
        datetime:
    action:
      name: Action
      description: Define the Action to trigger. Same syntax as Automation and Scripts
      required: true
      selector:
        action:

delete_schedule:
  name: Delete a Schedule
  description: Delete a previously scheduled action.
  fields:
    id:
      name: ID
      description: ID of the schedule to delete.
      required: true
      example: my_id_24578
      selector:
        text:
