#!/usr/bin/env bash
# Setups the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -n "$DEVCONTAINER" ] && [ ! -n "$VIRTUAL_ENV" ];then
  python3 -m venv venv
  source venv/bin/activate
fi

scripts/bootstrap

pre-commit install
pre-commit install --install-hooks -t commit-msg